[workspace]
resolver = "2"
members = [
    "logger",
    "redis_client",
    "redis_node",
    "ui_client",
    "cli",
    "common",
    "tests",
    "documents-handler-service",
    "microservice_llm",
    "json",
    "interpretefth"
, "events"]
