[package]
name = "redis_node"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
hex = "0.4.3"
redis_client = {path = "../redis_client", version = "0.1.0"}
common = { path = "../common", version = "0.1.0"}
logger = { path = "../logger", version = "0.1.0"}
glob = "0.3.2"
