pub(crate) mod cluster_message;
pub(crate) mod estructuras_failover;
pub(crate) mod handshake;
mod hilo_handler_connection;
mod hilo_ping_pong;
mod hilo_process_message;
mod hilo_read_message;
pub(crate) mod interconnection;
pub(crate) mod neighboring_node;
pub(crate) mod node_message;
pub(crate) mod replica_promotion;
pub(crate) mod utils;
pub(crate) mod voto;
